### ISSUE TITLE
GitLab [self managed] integration

### ISSUE THREAD

**Issue by gavinc1980** [github-changelog-generator/github-changelog-generator#761] opened 2020-02-04 12:09 UTC
Hello,

I see some people have been able to get this running on GitLab. The readme only shows github.

Can anyone advise how to get this runnning with GitLab self managed?

Would love to start using this tool

**Comment by skywinder** [comment] 2020-02-21 09:44
duplicate of https://github.com/github-changelog-generator/github-changelog-generator/issues/419

**Closed by skywinder** 2020-02-21 09:44 UTC
