### ISSUE TITLE
old merged PR listed for a wrong release

### ISSUE THREAD

**Issue by matkoniecz** [github-changelog-generator/github-changelog-generator#256] opened 2015-08-02 12:11 UTC
PR with old commit that waited for a long time before merging may be listed for wrong release.

For example `github_changelog_generator gravitystorm/openstreetmap-carto --no-issues` lists adding antarctic icesheet rendering based on preprocessed shapefiles (https://github.com/gravitystorm/openstreetmap-carto/pull/1540) for v2.30 instead of v2.32 - see https://github.com/gravitystorm/openstreetmap-carto/compare/v2.31.0...v2.32.0

**Comment by skywinder** [comment] 2015-08-03 06:15
@matkoniecz the PR appears in the next version tag after merging, isn't it?

You can manually specify in which version PR was merged by setting milestone of PR  the same name as tag of required version.

p.s.
Any ideas, how to detect, in under which tag this PR should presented?

**Comment by pnorman** [comment] 2015-08-03 09:05
We don't use milestones in that way.

> Any ideas, how to detect, in under which tag this PR should presented?

The earliest tag where all the commits in the PR are present

**Comment by skywinder** [comment] 2015-08-03 09:14
@pnorman I don't think that it will be correct behaviour in most of the cases. 
If PR is merged after tag is placed in general it means that this feature will appear in next release.

**Comment by pnorman** [comment] 2015-08-03 09:35
I generated a [changelog](https://gist.github.com/pnorman/962619427ba90e134873), and gravitystorm/openstreetmap-carto#1540 appears under v2.30.0. This PR only had one commit, https://github.com/gravitystorm/openstreetmap-carto/commit/89301f1394698e6634d58092f68e156e73e7cd38

If you look at the tags this is part of on the web interface, it is only part of v2.32.0. You can verify this with `git name-rev --tags 89301f1394698e6634d58092f68e156e73e7cd38` which shows it is `tags/v2.32.0~6^2`

**Comment by skywinder** [comment] 2015-08-03 10:41
@pnorman not matter, when it was committed. Because it could be long-term feature, that developer prepare for next releases. In that case determining by last commit will be incorrect.
And I can be sure for 100% that this feature in production only after merging of related branch.

**Comment by pnorman** [comment] 2015-08-03 11:13
`git name-rev` unambiguously tells you that it is part of v2.32.0

> @pnorman not matter, when it was committed

I'm not sure what you're trying to say here. If you're trying to say the commit date doesn't matter, that is correct. e.g. "especially since comparing commit dates in a project’s history doesn’t necessarily correspond to the order in which they were applied" from http://mislav.uniqpath.com/2010/07/git-tips/

**Comment by Oscil8** [comment] 2015-08-10 20:18
I've seen a similar issue when needing to push a patch for an old release; patches applied on the mainline before the patch (v0.11.1) are showing up in the changelog there instead of v0.12.0 which is where they actually got released. Sorry, this was a private repo but I can probably generate an example in a simple repository.

**Comment by skywinder** [comment] 2015-08-24 11:53
@Oscil8 it would be great, if you can provide some examples.
I'm using https://github.com/skywinder/changelog_test/ repo to test change log behaviour. If you can reproduce this case in this repo - it would significantly helps me to understand this issue. 
I can get you access to this repo to create necessary tags, commits and issues.

**Comment by skywinder** [comment] 2015-09-01 06:23
@matkoniecz  This error could related with #271. Please check, how it works now!

**Comment by matkoniecz** [comment] 2015-09-01 07:18
"adding antarctic icesheet rendering based on preprocessed shapefiles #1540 (imagico)" is still listed for v.2.30.0

**Comment by aparraga** [comment] 2016-11-14 12:41
same issue here!
I commit my changes in #78 branch and I commit a pull request against master. After that, someone label master with 3.0.4 (but #78 is still pending to merge, nobody has review the pull request). After releasing the 3.0.4 someone reviewed and merge the #78 in master. And the next time the CHANGELOG is generated, the #78 is under the 3.0.4 automagically. I don't think that this is the expected behavior, but having the #78 as part of the next release

**Comment by skywinder** [comment] 2016-11-22 13:47
@aparraga  which repository are you talking about? let me have a look on it.

**Comment by mvz** [comment] 2024-01-02 18:54
I have just tested this, and with the current release of `github_changelog_generator`, the pull request from openstreetmap-carto is now correctly listed under release 2.32.0.

So, this ticket can be closed.

/cc @olleolleolle

**Closed** 2024-01-03 08:21 UTC
Labels: bug
